/**
 * Mini App manifest.
 *
 * Base App and Farcaster read this to verify ownership and list the app. The
 * `accountAssociation` block is generated by `npx create-onchain --manifest`
 * after the first deploy; until then the app still runs, it just isn't verified.
 */

import { NextResponse } from 'next/server';

export async function GET() {
  const url = process.env.NEXT_PUBLIC_URL ?? 'http://localhost:3000';

  return NextResponse.json({
    accountAssociation: {
      header: process.env.FARCASTER_HEADER ?? '',
      payload: process.env.FARCASTER_PAYLOAD ?? '',
      signature: process.env.FARCASTER_SIGNATURE ?? '',
    },
    frame: {
      version: '1',
      name: 'Base Wallet Lens',
      subtitle: 'Your onchain history, read back to you',
      description:
        'Transactions, ETH spent on gas, first and last day, longest streak, bridged ETH and builder signals for any wallet on Base.',
      iconUrl: `${url}/icon.png`,
      homeUrl: url,
      imageUrl: `${url}/og.png`,
      splashImageUrl: `${url}/icon.png`,
      splashBackgroundColor: '#0A0B0D',
      primaryCategory: 'developer-tools',
      tags: ['analytics', 'wallet', 'base', 'explorer', 'stats'],
      tagline: 'Read any wallet on Base',
      ogTitle: 'Base Wallet Lens',
      ogDescription: 'Read any wallet’s full history on Base.',
      ogImageUrl: `${url}/og.png`,
    },
  });
}
